name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Downgrade to Node.js v18 (LTS)

      - name: Install dependencies
        run: yarn install

      - name: Update Browserslist database
        run: npx browserslist@latest --update-db  # Add this step

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Adjust this based on your output directory
          publish_branch: master  # Use `publish_branch` instead of `target_branch`
