name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Make sure the node version matches your project

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn run build

      - name: Deploy to GitHub Pages
        run: |
          cd docs
          echo 'manuelmejia.io' > CNAME
          cd ..
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy from GitHub Actions"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/manuelmejiaio/personal-website master
